networks:
  kafka-net:
    driver: bridge
  cassandra-net: 
    driver: bridge
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # ---- KRaft mode ----
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ

      # ---- Listeners ----
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ---- Single-node safe settings ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - kafka-net
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-net
  
  cassandra-db-1: 
    image: cassandra:4.1.3
    container_name: cassandra-instance-1
    ports:
      - 7000:7000
      - 9042:9042
      - 7199:7199
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
    restart:
      on-failure
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      start_period: 2m
      timeout: 30s
      retries: 3
    
  cassandra-db-2: 
    image: cassandra:4.1.3
    container_name: cassandra-instance-2
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-db-1
    restart:
      on-failure
    depends_on: 
      cassandra-db-1:
        condition: service_healthy
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      start_period: 2m
      timeout: 30s
      retries: 3
  cassandra-db-3: 
    image: cassandra:4.1.3 
    container_name: cassandra-instance-3
    ports:
      - 9044:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - CASSANDRA_SEEDS=cassandra-db-1
    restart:
      on-failure
    depends_on: 
      cassandra-db-2:
        condition: service_healthy
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status || exit 1"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3